version: 2.1

executors:
  worker:
    docker:
      - image: fr3akyphantom/droid-builder:latest
        auth:
          username: "$DOCKERHUB_USERNAME"
          password: "$DOCKERHUB_PASSWORD"

jobs:
  build:
    executor: worker
    environment:
      MANIFEST_BRANCH: 'android-6.0'
      #PBRP_BRANCH: 'android-9.0'
      #VERSION: '3.0.0'
      VENDOR: 'WALTON'
      CODENAME: 'Primo_RX5'
      FLAVOR: 'userdebug'
      MAINTAINER: '@fr3akyphantom'
      #CHANGELOG: ""
      TEST_BUILD: 'true'
      # Trim down PB_GO a little more
      # PB_GO: 'true' # If needed
      PB_ENGLISH: 'true'
      # PB_TORCH_PATH: '/sys/class/flashlightdrv/kd_camera_flashlight/torch'
      # EXTRA_CMD: ''
    working_directory: /home/builder/pitchblack

    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 'android-6.0-dev'
