version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest # Use Ubuntu Bionic for now, Focal has python2 issue
    environment:
      MANIFEST_BRANCH: 'twrp-6.0'
      USE_SECRET_BOOTABLE: "yes"
      PBRP_BRANCH: 'features' # ust to test if the bypass works or not
      # VERSION: '2.9.1' # Will fetch from pb_build.sh
      VENDOR: 'WALTON'
      CODENAME: 'Primo_RX5'
      BUILD_LUNCH: 'omni_Primo_RX5-userdebug'
      TEST_BUILD: 'true'
      # Trim down PB_GO a little more
      PB_ENGLISH: 'true'
      # PB_TORCH_PATH: '/sys/class/flashlightdrv/kd_camera_flashlight/torch'
      # EXTRA_CMD: ''
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global credential.helper store
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_pb/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 'test'
